<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
			array('code' => 'US', 'name' => 'United States','created_by' => 1),
			array('code' => 'CA', 'name' => 'Canada','created_by' => 1),
			array('code' => 'AF', 'name' => 'Afghanistan','created_by' => 1),
			array('code' => 'AL', 'name' => 'Albania','created_by' => 1),
			array('code' => 'DZ', 'name' => 'Algeria','created_by' => 1),
			array('code' => 'AS', 'name' => 'American Samoa','created_by' => 1),
			array('code' => 'AD', 'name' => 'Andorra','created_by' => 1),
			array('code' => 'AO', 'name' => 'Angola','created_by' => 1),
			array('code' => 'AI', 'name' => 'Anguilla','created_by' => 1),
			array('code' => 'AQ', 'name' => 'Antarctica','created_by' => 1),
			array('code' => 'AG', 'name' => 'Antigua and/or Barbuda','created_by' => 1),
			array('code' => 'AR', 'name' => 'Argentina','created_by' => 1),
			array('code' => 'AM', 'name' => 'Armenia','created_by' => 1),
			array('code' => 'AW', 'name' => 'Aruba','created_by' => 1),
			array('code' => 'AU', 'name' => 'Australia','created_by' => 1),
			array('code' => 'AT', 'name' => 'Austria','created_by' => 1),
			array('code' => 'AZ', 'name' => 'Azerbaijan','created_by' => 1),
			array('code' => 'BS', 'name' => 'Bahamas','created_by' => 1),
			array('code' => 'BH', 'name' => 'Bahrain','created_by' => 1),
			array('code' => 'BD', 'name' => 'Bangladesh','created_by' => 1),
			array('code' => 'BB', 'name' => 'Barbados','created_by' => 1),
			array('code' => 'BY', 'name' => 'Belarus','created_by' => 1),
			array('code' => 'BE', 'name' => 'Belgium','created_by' => 1),
			array('code' => 'BZ', 'name' => 'Belize','created_by' => 1),
			array('code' => 'BJ', 'name' => 'Benin','created_by' => 1),
			array('code' => 'BM', 'name' => 'Bermuda','created_by' => 1),
			array('code' => 'BT', 'name' => 'Bhutan','created_by' => 1),
			array('code' => 'BO', 'name' => 'Bolivia','created_by' => 1),
			array('code' => 'BA', 'name' => 'Bosnia and Herzegovina','created_by' => 1),
			array('code' => 'BW', 'name' => 'Botswana','created_by' => 1),
			array('code' => 'BV', 'name' => 'Bouvet Island','created_by' => 1),
			array('code' => 'BR', 'name' => 'Brazil','created_by' => 1),
			array('code' => 'IO', 'name' => 'British lndian Ocean Territory','created_by' => 1),
			array('code' => 'BN', 'name' => 'Brunei Darussalam','created_by' => 1),
			array('code' => 'BG', 'name' => 'Bulgaria','created_by' => 1),
			array('code' => 'BF', 'name' => 'Burkina Faso','created_by' => 1),
			array('code' => 'BI', 'name' => 'Burundi','created_by' => 1),
			array('code' => 'KH', 'name' => 'Cambodia','created_by' => 1),
			array('code' => 'CM', 'name' => 'Cameroon','created_by' => 1),
			array('code' => 'CV', 'name' => 'Cape Verde','created_by' => 1),
			array('code' => 'KY', 'name' => 'Cayman Islands','created_by' => 1),
			array('code' => 'CF', 'name' => 'Central African Republic','created_by' => 1),
			array('code' => 'TD', 'name' => 'Chad','created_by' => 1),
			array('code' => 'CL', 'name' => 'Chile','created_by' => 1),
			array('code' => 'CN', 'name' => 'China','created_by' => 1),
			array('code' => 'CX', 'name' => 'Christmas Island','created_by' => 1),
			array('code' => 'CC', 'name' => 'Cocos (Keeling) Islands','created_by' => 1),
			array('code' => 'CO', 'name' => 'Colombia','created_by' => 1),
			array('code' => 'KM', 'name' => 'Comoros','created_by' => 1),
			array('code' => 'CG', 'name' => 'Congo','created_by' => 1),
			array('code' => 'CK', 'name' => 'Cook Islands','created_by' => 1),
			array('code' => 'CR', 'name' => 'Costa Rica','created_by' => 1),
			array('code' => 'HR', 'name' => 'Croatia (Hrvatska)','created_by' => 1),
			array('code' => 'CU', 'name' => 'Cuba','created_by' => 1),
			array('code' => 'CY', 'name' => 'Cyprus','created_by' => 1),
			array('code' => 'CZ', 'name' => 'Czech Republic','created_by' => 1),
			array('code' => 'CD', 'name' => 'Democratic Republic of Congo','created_by' => 1),
			array('code' => 'DK', 'name' => 'Denmark','created_by' => 1),
			array('code' => 'DJ', 'name' => 'Djibouti','created_by' => 1),
			array('code' => 'DM', 'name' => 'Dominica','created_by' => 1),
			array('code' => 'DO', 'name' => 'Dominican Republic','created_by' => 1),
			array('code' => 'TP', 'name' => 'East Timor','created_by' => 1),
			array('code' => 'EC', 'name' => 'Ecudaor','created_by' => 1),
			array('code' => 'EG', 'name' => 'Egypt','created_by' => 1),
			array('code' => 'SV', 'name' => 'El Salvador','created_by' => 1),
			array('code' => 'GQ', 'name' => 'Equatorial Guinea','created_by' => 1),
			array('code' => 'ER', 'name' => 'Eritrea','created_by' => 1),
			array('code' => 'EE', 'name' => 'Estonia','created_by' => 1),
			array('code' => 'ET', 'name' => 'Ethiopia','created_by' => 1),
			array('code' => 'FK', 'name' => 'Falkland Islands (Malvinas)','created_by' => 1),
			array('code' => 'FO', 'name' => 'Faroe Islands','created_by' => 1),
			array('code' => 'FJ', 'name' => 'Fiji','created_by' => 1),
			array('code' => 'FI', 'name' => 'Finland','created_by' => 1),
			array('code' => 'FR', 'name' => 'France','created_by' => 1),
			array('code' => 'FX', 'name' => 'France, Metropolitan','created_by' => 1),
			array('code' => 'GF', 'name' => 'French Guiana','created_by' => 1),
			array('code' => 'PF', 'name' => 'French Polynesia','created_by' => 1),
			array('code' => 'TF', 'name' => 'French Southern Territories','created_by' => 1),
			array('code' => 'GA', 'name' => 'Gabon','created_by' => 1),
			array('code' => 'GM', 'name' => 'Gambia','created_by' => 1),
			array('code' => 'GE', 'name' => 'Georgia','created_by' => 1),
			array('code' => 'DE', 'name' => 'Germany','created_by' => 1),
			array('code' => 'GH', 'name' => 'Ghana','created_by' => 1),
			array('code' => 'GI', 'name' => 'Gibraltar','created_by' => 1),
			array('code' => 'GR', 'name' => 'Greece','created_by' => 1),
			array('code' => 'GL', 'name' => 'Greenland','created_by' => 1),
			array('code' => 'GD', 'name' => 'Grenada','created_by' => 1),
			array('code' => 'GP', 'name' => 'Guadeloupe','created_by' => 1),
			array('code' => 'GU', 'name' => 'Guam','created_by' => 1),
			array('code' => 'GT', 'name' => 'Guatemala','created_by' => 1),
			array('code' => 'GN', 'name' => 'Guinea','created_by' => 1),
			array('code' => 'GW', 'name' => 'Guinea-Bissau','created_by' => 1),
			array('code' => 'GY', 'name' => 'Guyana','created_by' => 1),
			array('code' => 'HT', 'name' => 'Haiti','created_by' => 1),
			array('code' => 'HM', 'name' => 'Heard and Mc Donald Islands','created_by' => 1),
			array('code' => 'HN', 'name' => 'Honduras','created_by' => 1),
			array('code' => 'HK', 'name' => 'Hong Kong','created_by' => 1),
			array('code' => 'HU', 'name' => 'Hungary','created_by' => 1),
			array('code' => 'IS', 'name' => 'Iceland','created_by' => 1),
			array('code' => 'IN', 'name' => 'India','created_by' => 1),
			array('code' => 'ID', 'name' => 'Indonesia','created_by' => 1),
			array('code' => 'IR', 'name' => 'Iran (Islamic Republic of)','created_by' => 1),
			array('code' => 'IQ', 'name' => 'Iraq','created_by' => 1),
			array('code' => 'IE', 'name' => 'Ireland','created_by' => 1),
			array('code' => 'IL', 'name' => 'Israel','created_by' => 1),
			array('code' => 'IT', 'name' => 'Italy','created_by' => 1),
			array('code' => 'CI', 'name' => 'Ivory Coast','created_by' => 1),
			array('code' => 'JM', 'name' => 'Jamaica','created_by' => 1),
			array('code' => 'JP', 'name' => 'Japan','created_by' => 1),
			array('code' => 'JO', 'name' => 'Jordan','created_by' => 1),
			array('code' => 'KZ', 'name' => 'Kazakhstan','created_by' => 1),
			array('code' => 'KE', 'name' => 'Kenya','created_by' => 1),
			array('code' => 'KI', 'name' => 'Kiribati','created_by' => 1),
			array('code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of','created_by' => 1),
			array('code' => 'KR', 'name' => 'Korea, Republic of','created_by' => 1),
			array('code' => 'KW', 'name' => 'Kuwait','created_by' => 1),
			array('code' => 'KG', 'name' => 'Kyrgyzstan','created_by' => 1),
			array('code' => 'LA', 'name' => 'Lao People\'s Democratic Republic','created_by' => 1),
			array('code' => 'LV', 'name' => 'Latvia','created_by' => 1),
			array('code' => 'LB', 'name' => 'Lebanon','created_by' => 1),
			array('code' => 'LS', 'name' => 'Lesotho','created_by' => 1),
			array('code' => 'LR', 'name' => 'Liberia','created_by' => 1),
			array('code' => 'LY', 'name' => 'Libyan Arab Jamahiriya','created_by' => 1),
			array('code' => 'LI', 'name' => 'Liechtenstein','created_by' => 1),
			array('code' => 'LT', 'name' => 'Lithuania','created_by' => 1),
			array('code' => 'LU', 'name' => 'Luxembourg','created_by' => 1),
			array('code' => 'MO', 'name' => 'Macau','created_by' => 1),
			array('code' => 'MK', 'name' => 'Macedonia','created_by' => 1),
			array('code' => 'MG', 'name' => 'Madagascar','created_by' => 1),
			array('code' => 'MW', 'name' => 'Malawi','created_by' => 1),
			array('code' => 'MY', 'name' => 'Malaysia','created_by' => 1),
			array('code' => 'MV', 'name' => 'Maldives','created_by' => 1),
			array('code' => 'ML', 'name' => 'Mali','created_by' => 1),
			array('code' => 'MT', 'name' => 'Malta','created_by' => 1),
			array('code' => 'MH', 'name' => 'Marshall Islands','created_by' => 1),
			array('code' => 'MQ', 'name' => 'Martinique','created_by' => 1),
			array('code' => 'MR', 'name' => 'Mauritania','created_by' => 1),
			array('code' => 'MU', 'name' => 'Mauritius','created_by' => 1),
			array('code' => 'TY', 'name' => 'Mayotte','created_by' => 1),
			array('code' => 'MX', 'name' => 'Mexico','created_by' => 1),
			array('code' => 'FM', 'name' => 'Micronesia, Federated States of','created_by' => 1),
			array('code' => 'MD', 'name' => 'Moldova, Republic of','created_by' => 1),
			array('code' => 'MC', 'name' => 'Monaco','created_by' => 1),
			array('code' => 'MN', 'name' => 'Mongolia','created_by' => 1),
			array('code' => 'MS', 'name' => 'Montserrat','created_by' => 1),
			array('code' => 'MA', 'name' => 'Morocco','created_by' => 1),
			array('code' => 'MZ', 'name' => 'Mozambique','created_by' => 1),
			array('code' => 'MM', 'name' => 'Myanmar','created_by' => 1),
			array('code' => 'NA', 'name' => 'Namibia','created_by' => 1),
			array('code' => 'NR', 'name' => 'Nauru','created_by' => 1),
			array('code' => 'NP', 'name' => 'Nepal','created_by' => 1),
			array('code' => 'NL', 'name' => 'Netherlands','created_by' => 1),
			array('code' => 'AN', 'name' => 'Netherlands Antilles','created_by' => 1),
			array('code' => 'NC', 'name' => 'New Caledonia','created_by' => 1),
			array('code' => 'NZ', 'name' => 'New Zealand','created_by' => 1),
			array('code' => 'NI', 'name' => 'Nicaragua','created_by' => 1),
			array('code' => 'NE', 'name' => 'Niger','created_by' => 1),
			array('code' => 'NG', 'name' => 'Nigeria','created_by' => 1),
			array('code' => 'NU', 'name' => 'Niue','created_by' => 1),
			array('code' => 'NF', 'name' => 'Norfork Island','created_by' => 1),
			array('code' => 'MP', 'name' => 'Northern Mariana Islands','created_by' => 1),
			array('code' => 'NO', 'name' => 'Norway','created_by' => 1),
			array('code' => 'OM', 'name' => 'Oman','created_by' => 1),
			array('code' => 'PK', 'name' => 'Pakistan','created_by' => 1),
			array('code' => 'PW', 'name' => 'Palau','created_by' => 1),
			array('code' => 'PA', 'name' => 'Panama','created_by' => 1),
			array('code' => 'PG', 'name' => 'Papua New Guinea','created_by' => 1),
			array('code' => 'PY', 'name' => 'Paraguay','created_by' => 1),
			array('code' => 'PE', 'name' => 'Peru','created_by' => 1),
			array('code' => 'PH', 'name' => 'Philippines','created_by' => 1),
			array('code' => 'PN', 'name' => 'Pitcairn','created_by' => 1),
			array('code' => 'PL', 'name' => 'Poland','created_by' => 1),
			array('code' => 'PT', 'name' => 'Portugal','created_by' => 1),
			array('code' => 'PR', 'name' => 'Puerto Rico','created_by' => 1),
			array('code' => 'QA', 'name' => 'Qatar','created_by' => 1),
			array('code' => 'SS', 'name' => 'Republic of South Sudan','created_by' => 1),
			array('code' => 'RE', 'name' => 'Reunion','created_by' => 1),
			array('code' => 'RO', 'name' => 'Romania','created_by' => 1),
			array('code' => 'RU', 'name' => 'Russian Federation','created_by' => 1),
			array('code' => 'RW', 'name' => 'Rwanda','created_by' => 1),
			array('code' => 'KN', 'name' => 'Saint Kitts and Nevis','created_by' => 1),
			array('code' => 'LC', 'name' => 'Saint Lucia','created_by' => 1),
			array('code' => 'VC', 'name' => 'Saint Vincent and the Grenadines','created_by' => 1),
			array('code' => 'WS', 'name' => 'Samoa','created_by' => 1),
			array('code' => 'SM', 'name' => 'San Marino','created_by' => 1),
			array('code' => 'ST', 'name' => 'Sao Tome and Principe','created_by' => 1),
			array('code' => 'SA', 'name' => 'Saudi Arabia','created_by' => 1),
			array('code' => 'SN', 'name' => 'Senegal','created_by' => 1),
			array('code' => 'RS', 'name' => 'Serbia','created_by' => 1),
			array('code' => 'SC', 'name' => 'Seychelles','created_by' => 1),
			array('code' => 'SL', 'name' => 'Sierra Leone','created_by' => 1),
			array('code' => 'SG', 'name' => 'Singapore','created_by' => 1),
			array('code' => 'SK', 'name' => 'Slovakia','created_by' => 1),
			array('code' => 'SI', 'name' => 'Slovenia','created_by' => 1),
			array('code' => 'SB', 'name' => 'Solomon Islands','created_by' => 1),
			array('code' => 'SO', 'name' => 'Somalia','created_by' => 1),
			array('code' => 'ZA', 'name' => 'South Africa','created_by' => 1),
			array('code' => 'GS', 'name' => 'South Georgia South Sandwich Islands','created_by' => 1),
			array('code' => 'ES', 'name' => 'Spain','created_by' => 1),
			array('code' => 'LK', 'name' => 'Sri Lanka','created_by' => 1),
			array('code' => 'SH', 'name' => 'St. Helena','created_by' => 1),
			array('code' => 'PM', 'name' => 'St. Pierre and Miquelon','created_by' => 1),
			array('code' => 'SD', 'name' => 'Sudan','created_by' => 1),
			array('code' => 'SR', 'name' => 'Suriname','created_by' => 1),
			array('code' => 'SJ', 'name' => 'Svalbarn and Jan Mayen Islands','created_by' => 1),
			array('code' => 'SZ', 'name' => 'Swaziland','created_by' => 1),
			array('code' => 'SE', 'name' => 'Sweden','created_by' => 1),
			array('code' => 'CH', 'name' => 'Switzerland','created_by' => 1),
			array('code' => 'SY', 'name' => 'Syrian Arab Republic','created_by' => 1),
			array('code' => 'TW', 'name' => 'Taiwan','created_by' => 1),
			array('code' => 'TJ', 'name' => 'Tajikistan','created_by' => 1),
			array('code' => 'TZ', 'name' => 'Tanzania, United Republic of','created_by' => 1),
			array('code' => 'TH', 'name' => 'Thailand','created_by' => 1),
			array('code' => 'TG', 'name' => 'Togo','created_by' => 1),
			array('code' => 'TK', 'name' => 'Tokelau','created_by' => 1),
			array('code' => 'TO', 'name' => 'Tonga','created_by' => 1),
			array('code' => 'TT', 'name' => 'Trinidad and Tobago','created_by' => 1),
			array('code' => 'TN', 'name' => 'Tunisia','created_by' => 1),
			array('code' => 'TR', 'name' => 'Turkey','created_by' => 1),
			array('code' => 'TM', 'name' => 'Turkmenistan','created_by' => 1),
			array('code' => 'TC', 'name' => 'Turks and Caicos Islands','created_by' => 1),
			array('code' => 'TV', 'name' => 'Tuvalu','created_by' => 1),
			array('code' => 'UG', 'name' => 'Uganda','created_by' => 1),
			array('code' => 'UA', 'name' => 'Ukraine','created_by' => 1),
			array('code' => 'AE', 'name' => 'United Arab Emirates','created_by' => 1),
			array('code' => 'GB', 'name' => 'United Kingdom','created_by' => 1),
			array('code' => 'UM', 'name' => 'United States minor outlying islands','created_by' => 1),
			array('code' => 'UY', 'name' => 'Uruguay','created_by' => 1),
			array('code' => 'UZ', 'name' => 'Uzbekistan','created_by' => 1),
			array('code' => 'VU', 'name' => 'Vanuatu','created_by' => 1),
			array('code' => 'VA', 'name' => 'Vatican City State','created_by' => 1),
			array('code' => 'VE', 'name' => 'Venezuela','created_by' => 1),
			array('code' => 'VN', 'name' => 'Vietnam','created_by' => 1),
			array('code' => 'VG', 'name' => 'Virgin Islands (British)','created_by' => 1),
			array('code' => 'VI', 'name' => 'Virgin Islands (U.S.)','created_by' => 1),
			array('code' => 'WF', 'name' => 'Wallis and Futuna Islands','created_by' => 1),
			array('code' => 'EH', 'name' => 'Western Sahara','created_by' => 1),
			array('code' => 'YE', 'name' => 'Yemen','created_by' => 1),
			array('code' => 'YU', 'name' => 'Yugoslavia','created_by' => 1),
			array('code' => 'ZR', 'name' => 'Zaire','created_by' => 1),
			array('code' => 'ZM', 'name' => 'Zambia','created_by' => 1),
			array('code' => 'ZW', 'name' => 'Zimbabwe','created_by' => 1),
		);

		DB::table('countries')->insert($countries);
    }
}
